name: CI-CD Local

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Installation et tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:lts
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: todolist_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

      # Récupération du code
      - name: Checkout du code
        uses: actions/checkout@v4

      # Installation Node.js
      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

          - name: Installation des dépendances npm
        run: npm ci

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -uroot -proot --silent; then
              echo "MySQL is up"
              exit 0
            fi
            echo "Waiting MySQL..."
            sleep 2
          done
          exit 1

      - name: Variables DB
        run: |
          echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "DB_USER=root" >> $GITHUB_ENV
          echo "DB_PASSWORD=root" >> $GITHUB_ENV
          echo "DB_NAME=todolist_db" >> $GITHUB_ENV
          echo "DB_DIALECT=mysql" >> $GITHUB_ENV

      - name: Correction permissions Jest
        run: |
          chmod +x node_modules/.bin/jest

      - name: Lancer les tests
        run: npx jest --runInBand